-- Baseline: the schema as JPA's ddl-auto:update had already created it.
--
-- Existing deployments never run this. Flyway's baseline-on-migrate marks a
-- non-empty schema at version 1 and starts from V2, so this file exists to give
-- a fresh database (a local run, a test, a rebuilt Postgres) the same starting
-- point the live one already reached. IF NOT EXISTS throughout for the same
-- reason: docker-compose seeds `teams` from database/init.sql before the
-- gateway ever starts.

CREATE TABLE IF NOT EXISTS teams (
    id               INTEGER PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    city             VARCHAR(100) NOT NULL,
    abbreviation     VARCHAR(10)  NOT NULL UNIQUE,
    conference       VARCHAR(10)  NOT NULL,
    division         VARCHAR(10)  NOT NULL,
    logo_url         VARCHAR(255),
    primary_color    VARCHAR(7),
    secondary_color  VARCHAR(7),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_weights (
    agent_name         VARCHAR(100) PRIMARY KEY,
    weight             DOUBLE PRECISION NOT NULL,
    measured_accuracy  DOUBLE PRECISION,
    calibration_window VARCHAR(50),
    is_calibrated      BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at         TIMESTAMP
);

CREATE TABLE IF NOT EXISTS predictions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id           BIGINT       NOT NULL,
    home_team         VARCHAR(100) NOT NULL,
    away_team         VARCHAR(100) NOT NULL,
    predicted_winner  VARCHAR(100) NOT NULL,
    confidence        DOUBLE PRECISION NOT NULL,
    consensus_method  VARCHAR(30),
    agent_detail      TEXT,
    created_at        TIMESTAMP    NOT NULL,
    actual_winner     VARCHAR(100),
    was_correct       BOOLEAN,
    settled           BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_predictions_game    ON predictions (game_id);
CREATE INDEX IF NOT EXISTS idx_predictions_settled ON predictions (settled);
